#!/usr/bin/env python3
"""Index recent Claude Code sessions for /ask-expert.

Scans ~/.claude/projects/**/*.jsonl, keeps the 100 most-recently-modified,
and for any session not already in the index (or whose mtime changed),
extracts a title + first user prompts and asks Haiku to produce a one-line
summary plus topic tags. Results are cached in data/index.json.
"""
import json
import os
import re
import subprocess
import sys
from pathlib import Path

PROJECTS_DIR = Path.home() / ".claude" / "projects"
PLUGIN_DIR = Path.home() / ".claude" / "plugins" / "ask-expert"
DATA_DIR = PLUGIN_DIR / "data"
INDEX_FILE = DATA_DIR / "index.json"
MAX_SESSIONS = 300  # how many recent sessions to scan for new classification;
# retention is independent — already-indexed sessions persist as long as their
# JSONL exists on disk (see main()).
BATCH_SIZE = 10


def extract_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        for part in content:
            if isinstance(part, dict) and part.get("type") == "text":
                return part.get("text", "")
    return ""


# First-prompt prefixes that indicate this session was created by the
# /ask-expert indexer or reranker itself — skip these entirely.
INDEXER_TEMPLATE_PREFIXES = (
    "Classify each Claude Code conversation",
    "Classify each conversation",
    "User's new question:",
    "Pick up to 3 sessions",
)

# Placeholders that don't carry topic signal; skip past them when collecting
# first prompts but don't treat their session as empty.
PLACEHOLDER_PREFIXES = (
    "[Request interrupted",
    "[Image #",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running",
    "<command-name>",
    "<command-message>",
    "<local-command",
)


def is_substantive(text):
    s = (text or "").lstrip()
    if not s:
        return False
    if s.startswith("<"):
        return False
    for p in PLACEHOLDER_PREFIXES:
        if s.startswith(p):
            return False
    return True


SEARCHABLE_CAP = 8000  # chars of concatenated user text retained for search


def parse_session(jsonl_path):
    """Return a dict with parsed session metadata, or {'skip': True} if the
    session is empty or was created by the /ask-expert indexer itself.

    Keys: title, cwd, forked_from, prompts, last_prompt, searchable_text, stats.
    `stats` has: user_msgs, assistant_msgs, tool_uses, total_chars.
    """
    title = None
    session_name = None
    cwd = None
    forked_from = None
    logical_parent_uuid = None
    prompts = []
    last_prompt = ""
    searchable_chunks = []
    searchable_len = 0
    user_msgs = 0
    assistant_msgs = 0
    tool_uses = 0
    total_chars = 0
    last_usage = None
    try:
        text = jsonl_path.read_text(errors="replace")
    except OSError:
        return {"skip": True}
    for line in text.splitlines():
        if not line.strip():
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        t = obj.get("type")
        if t == "ai-title":
            title = obj.get("aiTitle")
        if t == "custom-title":
            # What `/rename` writes. Claude appends a fresh record on every
            # rename, so the LAST one wins. This is the name `claude --resume`
            # accepts in place of a UUID.
            session_name = obj.get("customTitle") or session_name
        if cwd is None:
            cwd = obj.get("cwd")
        if forked_from is None:
            ff = obj.get("forkedFrom")
            if isinstance(ff, dict):
                forked_from = ff.get("sessionId")
        if logical_parent_uuid is None and obj.get("logicalParentUuid"):
            logical_parent_uuid = obj.get("logicalParentUuid")
        if t == "user" and not obj.get("isMeta"):
            user_msgs += 1
            msg = obj.get("message", {})
            content = msg.get("content", "")
            text_val = extract_text(content)
            total_chars += len(text_val)
            if not is_substantive(text_val):
                continue
            stripped = text_val.lstrip()
            if any(stripped.startswith(p) for p in INDEXER_TEMPLATE_PREFIXES):
                return {"skip": True}
            if len(prompts) < 3:
                prompts.append(text_val[:600])
            last_prompt = text_val[:1200]
            if searchable_len < SEARCHABLE_CAP:
                chunk = text_val[: SEARCHABLE_CAP - searchable_len]
                searchable_chunks.append(chunk)
                searchable_len += len(chunk)
        elif t == "assistant":
            assistant_msgs += 1
            msg = obj.get("message", {})
            content = msg.get("content", "")
            text_val = extract_text(content)
            total_chars += len(text_val)
            if isinstance(content, list):
                for part in content:
                    if isinstance(part, dict) and part.get("type") == "tool_use":
                        tool_uses += 1
            u = msg.get("usage")
            if isinstance(u, dict):
                total = (
                    (u.get("input_tokens") or 0)
                    + (u.get("cache_read_input_tokens") or 0)
                    + (u.get("cache_creation_input_tokens") or 0)
                )
                if total > 0:
                    last_usage = u
    if not prompts:
        return {"skip": True}

    # Compute the true live-context size from the latest assistant API usage.
    # This matches what claude's own `/context` command reports.
    current_tokens = None
    if last_usage:
        current_tokens = (
            (last_usage.get("input_tokens") or 0)
            + (last_usage.get("cache_read_input_tokens") or 0)
            + (last_usage.get("cache_creation_input_tokens") or 0)
        )

    return {
        "title": title,
        "session_name": session_name,
        "cwd": cwd,
        "forked_from": forked_from,
        "logical_parent_uuid": logical_parent_uuid,
        "prompts": prompts,
        "last_prompt": last_prompt,
        "searchable_text": "\n".join(searchable_chunks),
        "stats": {
            "user_msgs": user_msgs,
            "assistant_msgs": assistant_msgs,
            "tool_uses": tool_uses,
            "total_chars": total_chars,
            "current_tokens": current_tokens,
        },
    }


def call_haiku(prompt, timeout=120):
    """Call `claude -p --model haiku` and return stdout."""
    try:
        result = subprocess.run(
            ["claude", "-p", "--model", "haiku", prompt],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return None
    if result.returncode != 0:
        print(f"claude -p failed: {result.stderr[:300]}", file=sys.stderr)
        return None
    return result.stdout.strip()


def strip_fences(text):
    text = text.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        # drop first fence line, and last if it's a fence
        lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines)
    return text.strip()


def classify_batch(items):
    """items: list of {id, title, prompts}. Returns dict id -> {summary, topics}."""
    if not items:
        return {}
    prompt = (
        "Classify each Claude Code conversation below. For each one, produce:\n"
        "- summary: ONE sentence describing what the user was working on\n"
        "- topics: 3-8 specific keyword/topic tags (e.g. \"rdma\", \"nixos-flake\", "
        "\"libcamera-ipa\", \"ffi-bindings\", \"github-pr-review\")\n\n"
        "Input (JSON array):\n"
        f"{json.dumps(items, indent=2)}\n\n"
        "Return ONLY a JSON object mapping each id to its classification:\n"
        '{"<id1>": {"summary": "...", "topics": ["..."]}, "<id2>": {...}}'
    )
    raw = call_haiku(prompt)
    if not raw:
        return {}
    raw = strip_fences(raw)
    # Tolerate prose before/after JSON: find the outermost {...}
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if not m:
        print(f"classify_batch: no JSON found in: {raw[:300]}", file=sys.stderr)
        return {}
    try:
        return json.loads(m.group(0))
    except json.JSONDecodeError as e:
        print(f"classify_batch: JSON parse error: {e}\n{raw[:300]}", file=sys.stderr)
        return {}


def read_session_name(path):
    """Last `custom-title` in a transcript, i.e. what `/rename` set, or None.

    Cheap on purpose: renames append, so the tail almost always holds the
    current value and we only fall back to a full read for smaller files.
    """
    try:
        size = os.path.getsize(path)
        with open(path, "rb") as fh:
            fh.seek(max(0, size - 512 * 1024))
            blob = fh.read().decode("utf8", "replace")
            if '"custom-title"' not in blob and 512 * 1024 < size <= 64 * 1024 * 1024:
                fh.seek(0)
                blob = fh.read().decode("utf8", "replace")
    except OSError:
        return None
    for line in reversed(blob.splitlines()):
        if '"custom-title"' not in line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if obj.get("type") == "custom-title" and obj.get("customTitle"):
            return obj["customTitle"]
    return None


def backfill_session_names(index):
    """Give entries written before session_name existed the field, without
    re-classifying them. Sets the key even when None so this runs once."""
    n = 0
    for sid, meta in index.get("sessions", {}).items():
        if "session_name" in meta:
            continue
        path = meta.get("path")
        meta["session_name"] = read_session_name(path) if path else None
        if meta["session_name"]:
            n += 1
    return n


def build_entry(sid, jsonl_path, mtime, parsed, classification=None):
    """Construct an index-entry dict from parse_session output."""
    cls = classification or {}
    return {
        "project": jsonl_path.parent.name,
        "path": str(jsonl_path),
        "cwd": parsed.get("cwd"),
        "mtime": mtime,
        "title": parsed.get("title"),
        "session_name": parsed.get("session_name"),
        "forked_from": parsed.get("forked_from"),
        "logical_parent_uuid": parsed.get("logical_parent_uuid"),
        "first_prompt": parsed["prompts"][0] if parsed["prompts"] else "",
        "last_prompt": parsed.get("last_prompt", ""),
        "summary": cls.get("summary", parsed.get("title") or "(awaiting classification)"),
        "topics": cls.get("topics", []),
        "searchable_text": parsed.get("searchable_text", ""),
        "stats": parsed.get("stats", {}),
    }


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    if INDEX_FILE.exists():
        try:
            index = json.loads(INDEX_FILE.read_text())
        except json.JSONDecodeError:
            index = {"version": 1, "sessions": {}}
    else:
        index = {"version": 1, "sessions": {}}

    all_on_disk = []
    # Only top-level <project>/<session>.jsonl files — skip subagent and
    # tool-result transcripts that live in subdirectories.
    for jsonl in PROJECTS_DIR.glob("*/*.jsonl"):
        try:
            mtime = jsonl.stat().st_mtime
        except OSError:
            continue
        all_on_disk.append((mtime, jsonl))
    all_on_disk.sort(key=lambda x: -x[0])

    # RETENTION: keep every already-indexed entry whose JSONL still exists on
    # disk. We only drop entries whose file is genuinely gone (deleted/trashed).
    # The recency cap below bounds *new classification work* only — it must
    # never evict an old session (especially a fork parent) from the index.
    on_disk_ids = {jsonl.stem for _, jsonl in all_on_disk}
    dropped = [k for k in index.get("sessions", {}) if k not in on_disk_ids]
    for k in dropped:
        index["sessions"].pop(k, None)
    if dropped:
        print(f"dropped {len(dropped)} entries whose file is gone", file=sys.stderr)

    filled = backfill_session_names(index)
    if filled:
        print(f"backfilled session_name on {filled} entries", file=sys.stderr)

    # CLASSIFICATION SCOPE: the most-recent MAX_SESSIONS by mtime, PLUS any
    # session referenced as a fork parent (so lineage targets always resolve).
    recent = all_on_disk[:MAX_SESSIONS]
    recent_ids = {jsonl.stem for _, jsonl in recent}
    lineage_path = DATA_DIR / "fork_lineage.json"
    parent_ids = set()
    if lineage_path.exists():
        try:
            parent_ids = set(json.loads(lineage_path.read_text()).values())
        except (json.JSONDecodeError, OSError):
            parent_ids = set()
    scan = list(recent)
    for mtime, jsonl in all_on_disk[MAX_SESSIONS:]:
        if jsonl.stem in parent_ids:
            scan.append((mtime, jsonl))

    to_classify = []
    for mtime, jsonl in scan:
        sid = jsonl.stem
        existing = index["sessions"].get(sid)
        # Re-classify if mtime changed, classification was empty, OR the entry
        # is missing any new schema fields.
        if (
            existing
            and existing.get("mtime") == mtime
            and existing.get("topics")
            and "searchable_text" in existing
            and "last_prompt" in existing
            and "stats" in existing
            and "logical_parent_uuid" in existing
        ):
            continue
        parsed = parse_session(jsonl)
        if parsed.get("skip"):
            continue
        to_classify.append((sid, jsonl, mtime, parsed))

    if not to_classify:
        INDEX_FILE.write_text(json.dumps(index, indent=2))
        print(
            f"index up to date ({len(index['sessions'])} sessions)", file=sys.stderr
        )
        return

    print(
        f"classifying {len(to_classify)} new/changed sessions in batches of {BATCH_SIZE}...",
        file=sys.stderr,
    )

    for start in range(0, len(to_classify), BATCH_SIZE):
        batch = to_classify[start : start + BATCH_SIZE]
        payload = [
            {
                "id": sid,
                "title": parsed.get("title") or "(untitled)",
                "first_prompts": parsed["prompts"],
            }
            for (sid, _, _, parsed) in batch
        ]
        classifications = classify_batch(payload)
        for sid, jsonl, mtime, parsed in batch:
            cls = classifications.get(sid, {})
            index["sessions"][sid] = build_entry(sid, jsonl, mtime, parsed, cls)

    def would_cycle(child, parent):
        """True if setting child.forked_from = parent creates a loop."""
        cursor = parent
        seen = {child}
        while cursor is not None:
            if cursor in seen:
                return True
            seen.add(cursor)
            cursor = index["sessions"].get(cursor, {}).get("forked_from")
        return False

    def set_parent(child, parent):
        if (
            child in index["sessions"]
            and parent
            and parent != child
            and parent in index["sessions"]
            and not index["sessions"][child].get("forked_from")
            and not would_cycle(child, parent)
        ):
            index["sessions"][child]["forked_from"] = parent
            return True
        return False

    resolved = 0

    # Lineage priority (highest first):
    #   1. real `forkedFrom` field (already set by parse_session)
    #   2. fork_lineage.json sidecar — explicit pins from create_fork.py and
    #      manual edits; AUTHORITATIVE, applied before logicalParentUuid so a
    #      user pin can't be flipped by an ambiguous auto-resolution.
    #   3. logicalParentUuid resolution (auto continuation linkage)
    lineage_path = DATA_DIR / "fork_lineage.json"
    if lineage_path.exists():
        try:
            lineage = json.loads(lineage_path.read_text())
        except (json.JSONDecodeError, OSError):
            lineage = {}
        for sid, parent in lineage.items():
            if set_parent(sid, parent):
                resolved += 1

    # Resolve logicalParentUuid → forked_from for anything still unparented.
    # `logicalParentUuid` is a message UUID (any type: user/assistant/system)
    # in some other session's JSONL. We find which JSONL contains it via a
    # targeted substring scan — UUIDs are globally unique so this is safe.
    unresolved = {}
    for sid, entry in index["sessions"].items():
        if entry.get("forked_from"):
            continue
        lpu = entry.get("logical_parent_uuid")
        if lpu:
            unresolved[sid] = lpu

    if unresolved:
        # Match the precise JSON field form so a UUID printed inside chat
        # text (in *this* indexer's own diagnostic output, say) doesn't
        # produce a false hit.
        targets = set(unresolved.values())
        needles = {t: (f'"uuid":"{t}"', f'"uuid": "{t}"') for t in targets}
        uuid_to_sid = {}
        for sid, entry in index["sessions"].items():
            if not targets:
                break
            path = entry.get("path")
            if not path:
                continue
            try:
                text = Path(path).read_text(errors="replace")
            except OSError:
                continue
            for t in list(targets):
                n1, n2 = needles[t]
                if n1 in text or n2 in text:
                    uuid_to_sid[t] = sid
                    targets.discard(t)

        for sid, lpu in unresolved.items():
            if set_parent(sid, uuid_to_sid.get(lpu)):
                resolved += 1

    INDEX_FILE.write_text(json.dumps(index, indent=2))
    msg = f"indexed {len(to_classify)} sessions; {len(index['sessions'])} total in index"
    if resolved:
        msg += f"; resolved {resolved} continuation parent(s) via logicalParentUuid"
    print(msg, file=sys.stderr)


if __name__ == "__main__":
    main()
